services:
  - type: web
    name: mindful-app
    env: python
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    plan: free
    buildImage: python:3.12-bullseye        # 👈 Force Render to use Python 3.12
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REALTIME_MODEL
        value: gpt-4o-realtime-preview-2024-12-17
    healthCheckPath: /api/health
